---
- name: Gather Info from Cisco Routers
  hosts: Routers
  gather_facts: no
  connection: network_cli

  vars:
  ansible_network_os: cisco.ios
  ansible_become: yes
  ansible_become_method: enable

  tasks:
    - name: Show hostname
      ios_command:
        commands:
          - show run | include hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout_lines

    - name: Show version
      ios_command:
        commands:
          - show version
      register: version_output

    - name: Display version
      debug:
        var: version_output.stdout_lines

    - name: Show interfaces
      ios_command:
        commands:
          - show ip interface brief
      register: int_output

    - name: Display interfaces
      debug:
        var: int_output.stdout_lines

    - name: Get IP routes
      ios_command:
        commands:
          - show ip route
      register: route_output

    - name: Filter routes only
      set_fact:
        routes: "{{ route_output.stdout_lines[0] | select('match','^[A-Z*]') | list }}"

    - name: Display routes
      debug:
        var: routes
