---
- name: Test Cisco Router with AWX
  hosts: Routers
  gather_facts: no
  connection: network_cli   # important for Cisco IOS

  tasks:

    - name: Gather IOS facts
      cisco.ios.ios_facts:

    - name: Show hostname
      debug:
        msg: "Router hostname is {{ ansible_net_hostname }}"

    - name: Show IOS version
      debug:
        msg: "Router IOS version is {{ ansible_net_version }}"
