---
- name: Configure Cisco Switches
  hosts: Switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - hostname SWITCH-ANSIBLE

    - name: Configure VLANs
      ios_config:
        lines:
          - vlan 10
          - name ADMIN
          - vlan 20
          - name STAFF

    - name: Assign access port to VLAN 10
      ios_config:
        lines:
          - interface GigabitEthernet0/2
          - switchport mode access
          - switchport access vlan 10

    - name: Configure Switch Virtual Interface (Loopback simulation)
      ios_config:
        lines:
          - interface loopback0
          - ip address 192.168.1.10 255.255.255.0
          - no shutdown

    - name: Configure MOTD banner
      ios_config:
        lines:
          - banner motd ^
          - Switch access restricted!
          - ^
