---
- name: Configure Cisco Switches
  hosts: Switches
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - hostname {{ hostname }}

    - name: Configure VLANs
      ios_config:
        lines:
          - vlan 10
          - name ADMIN
          - vlan 20
          - name STAFF

    - name: Assign access port to VLAN 10/20
      ios_config:
        parents:
          - interface range GigabitEthernet0/2-3,GigabitEthernet1/0-3,GigabitEthernet2/0-3
        lines:
          - switchport mode access
          - switchport access vlan {{ access_port }}

    - name: Configure MOTD banner
      ios_config:
        lines:
          - banner motd ^ 
            Switch access restricted!
            Unauthorized access prohibited!
            ^



